// Generated by CoffeeScript 1.11.1
var cheerio, request, url;

request = require('request');

cheerio = require('cheerio');

url = require('../api').url;

module.exports = function(id, pw, callback) {
  var options;
  options = {
    url: url.login,
    form: {
      mail_tel: id,
      password: pw
    }
  };
  return request.post(options, (function(_this) {
    return function(error, res, body) {
      var cookie, cookieValue, cookies, i, len, value;
      if (error != null) {
        return callback(error);
      }
      cookies = res.headers['set-cookie'];
      for (i = 0, len = cookies.length; i < len; i++) {
        value = cookies[i];
        if (value.indexOf('user_session=user_session') === 0) {
          cookie = value;
        }
      }
      if (cookie == null) {
        cookie = '';
      }
      cookieValue = cookie.slice(0, cookie.indexOf(';') + 1);
      if (cookieValue === '') {
        return callback('Invalid user');
      }
      _this.set(cookieValue);
      _this.save();
      return callback(null, cookieValue);
    };
  })(this));
};
