// Generated by CoffeeScript 1.11.1
var request, url;

request = require('request');

url = require('../api').url;

module.exports = function(callback) {
  var options;
  options = {
    url: url.logout,
    headers: {
      Cookie: this.get()
    },
    followRedirect: false
  };
  return request(options, (function(_this) {
    return function(error, res) {
      if (error != null) {
        return callback(error);
      }
      _this.destroy();
      return callback(null, res.statusCode);
    };
  })(this));
};
